export enum ErrorCode {
  CAN_NOT_LOGIN = 'Can not login',
  REFRESH_TOKEN_WRONG = 'Refresh token wrong',
  TOKEN_INVALID = 'TOKEN_INVALID',
  USER_HAS_BANNED = 'USER_HAS_BANNED',
  CAN_NOT_REGISTER_RC_CHAT = 'CAN_NOT_REGISTER_RC_CHAT',
  CAN_NOT_FOUND_USER = 'CAN_NOT_FOUND_USER',
  CAN_NOT_FETCH_API = 'CAN_NOT_FETCH_API',
}
